# RoadRunner配置文件示例
# 更多配置选项请参考: https://roadrunner.dev/docs

version: "3"

# RPC配置
rpc:
  listen: tcp://127.0.0.1:6001

# 服务器配置
server:
  command: "php worker.php"
  user: ""
  group: ""
  env:
    - APP_ENV: production
  relay: "pipes"
  relay_timeout: "20s"

# HTTP配置
http:
  address: 0.0.0.0:8080
  middleware: ["static", "gzip"]
  uploads:
    forbid: [".php", ".exe", ".bat"]
  trusted_subnets:
    - "10.0.0.0/8"
    - "127.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"
    - "::1/128"
    - "fc00::/7"
    - "fe80::/10"
  static:
    dir: "public"
    forbid: [".htaccess", ".php"]
    request:
      input: 1024
      output: 1024
    response:
      output: 1024

# 日志配置
logs:
  mode: production
  level: error
  file_logger_options:
    log_output: "runtime/roadrunner.log"
    max_size: 10
    max_age: 30
    max_backups: 3
    compress: true

# 指标配置
metrics:
  address: localhost:2112

# 健康检查
status:
  address: localhost:2114

# 进程池配置
pool:
  num_workers: 4
  max_jobs: 0
  allocate_timeout: 60s
  destroy_timeout: 60s
  supervisor:
    watch_tick: 1s
    ttl: 0s
    idle_ttl: 10s
    exec_ttl: 60s
    max_worker_memory: 128

# 限流配置
limit:
  interval: 60
  services:
    http:
      max_memory: 100
      ttl: 60s
      interval: 60s

# 重载配置
reload:
  interval: 1s
  patterns: [".php"]
  services:
    http:
      recursive: true
      ignore: ["vendor"]
      patterns: [".php", ".go", ".md"]
      dirs: ["./"]
